language: java

jdk:
  - openjdk8

os:
  - linux

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script: ./gradlew clean build --refresh-dependencies --stacktrace

deploy:
  provider: script
  skip_cleanup: true
  script: ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
  on:
    branch: master